spring:
  datasource:
    url: jdbc:mysql://192.168.18.131:3306/smelt?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: smelt
    password: smelt@jingnuo#2018
    #      url: jdbc:mysql://39.105.176.49:3306/smelt?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    #      username: root
    #      password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    test-while-idle: true
    validation-query: SELECT 1